### è‡ªåŠ¨æ›´æ–°é…ç½®
```yaml
name: Profile Stats
on:
  schedule:
    - cron: "0 12 * * *" # æ¯å¤©UTCæ—¶é—´12ç‚¹æ›´æ–°
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - name: Calculate GitHub Age
        run: |
          CREATED_AT=$(curl -s https://api.github.com/users/houzhaohan | grep 'created_at' | cut -d'"' -f4)
          START_DATE=$(date -d "$CREATED_AT" +%Y-%m-%d)
          DAYS=$(( ($(date +%s) - $(date -d "$START_DATE" +%s)) / 86400 ))
          echo "DAYS_SINCE_CREATION=$DAYS" >> $GITHUB_ENV
      
      - name: Update README
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs').promises;
            let content = await fs.readFile('README.md', 'utf8');
            const newContent = content.replace(/ðŸŒ± Account Age:.*?\.\.\./, `ðŸŒ± Account Age:    ${process.env.DAYS_SINCE_CREATION} days`);
            await fs.writeFile('README.md', newContent);
