name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@master
        with:
          github_user_name: houzhaohan
          svg_output_path: dist/github-contribution-grid-snake.svg
      - uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: main
          folder: dist
